//
//  PlatformShowcaseTests.swift
//  PlatformShowcaseTests
//
//  Generated by the ConcordUI command-line tool.
//

import Testing

struct PlatformShowcaseTests {
    @Test func projectLoads() async throws {
        #expect(true)
    }
}