//
//  HelloConcordUIApp.swift
//  HelloConcordUI
//
//  Generated by the ConcordUI command-line tool.
//

import ConcordUI
import ConcordUIApple
import SwiftUI

@main
struct HelloConcordUIApp: App {
    private let platform: ConcordApplePlatform
    private let application: HelloConcordUIApplication

    init() {
        let platform = ConcordApplePlatform()
        self.platform = platform

        let application = HelloConcordUIApplication(platform: platform)
        self.application = application
        application.startApplication()
    }

    var body: some Scene {
        ConcordAppleScene(platform: platform, application: application)
    }
}