//
//  HelloConcordUITests.swift
//  HelloConcordUITests
//
//  Generated by the ConcordUI command-line tool.
//

import Testing

struct HelloConcordUITests {
    @Test func projectLoads() async throws {
        #expect(true)
    }
}