//
//  ElementShowcaseApp.swift
//  ElementShowcase
//
//  Generated by the ConcordUI command-line tool.
//

import ConcordUI
import ConcordUIApple
import SwiftUI

@main
struct ElementShowcaseApp: App {
    private let platform: ConcordApplePlatform
    private let application: ElementShowcaseApplication

    init() {
        let platform = ConcordApplePlatform()
        self.platform = platform

        let application = ElementShowcaseApplication(platform: platform)
        self.application = application
        application.startApplication()
    }

    var body: some Scene {
        ConcordAppleScene(platform: platform, application: application)
    }
}