//
//  PresentationShowcaseApp.swift
//  PresentationShowcase
//
//  Generated by the ConcordUI command-line tool.
//

import ConcordUI
import ConcordUIApple
import SwiftUI

@main
struct PresentationShowcaseApp: App {
    private let platform: ConcordApplePlatform
    private let application: PresentationShowcaseApplication

    init() {
        let platform = ConcordApplePlatform()
        self.platform = platform

        let application = PresentationShowcaseApplication(platform: platform)
        self.application = application
        application.startApplication()
    }

    var body: some Scene {
        ConcordAppleScene(platform: platform, application: application)
    }
}