//
//  PlatformShowcaseApp.swift
//  PlatformShowcase
//
//  Generated by the ConcordUI command-line tool.
//

import ConcordUI
import ConcordUIApple
import SwiftUI

@main
struct PlatformShowcaseApp: App {
    private let platform: ConcordApplePlatform
    private let application: PlatformShowcaseApplication

    init() {
        let platform = ConcordApplePlatform()
        self.platform = platform

        let application = PlatformShowcaseApplication(platform: platform)
        self.application = application
        application.startApplication()
    }

    var body: some Scene {
        ConcordAppleScene(platform: platform, application: application)
    }
}