//
//  PlatformShowcaseUITests.swift
//  PlatformShowcaseUITests
//
//  Generated by the ConcordUI command-line tool.
//

import XCTest

final class PlatformShowcaseUITests: XCTestCase {
    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    func testLaunch() throws {
        let app = XCUIApplication()
        app.launch()
        XCTAssertTrue(app.wait(for: .runningForeground, timeout: 5))
    }
}