//
//  ElementShowcaseTests.swift
//  ElementShowcaseTests
//
//  Generated by the ConcordUI command-line tool.
//

import Testing

struct ElementShowcaseTests {
    @Test func projectLoads() async throws {
        #expect(true)
    }
}