//
//  VenueShowcaseApp.swift
//  VenueShowcase
//
//  Generated by the ConcordUI command-line tool.
//

import ConcordUI
import ConcordUIApple
import SwiftUI

@main
struct VenueShowcaseApp: App {
    private let platform: ConcordApplePlatform
    private let application: VenueShowcaseApplication

    init() {
        let platform = ConcordApplePlatform()
        self.platform = platform

        let application = VenueShowcaseApplication(platform: platform)
        self.application = application
        application.startApplication()
    }

    var body: some Scene {
        ConcordAppleScene(platform: platform, application: application)
    }
}