//
//  PresentationShowcaseTests.swift
//  PresentationShowcaseTests
//
//  Generated by the ConcordUI command-line tool.
//

import Testing

struct PresentationShowcaseTests {
    @Test func projectLoads() async throws {
        #expect(true)
    }
}