//
//  VenueShowcaseTests.swift
//  VenueShowcaseTests
//
//  Generated by the ConcordUI command-line tool.
//

import Testing

struct VenueShowcaseTests {
    @Test func projectLoads() async throws {
        #expect(true)
    }
}