//
//  FeaturesShowcaseTests.swift
//  FeaturesShowcaseTests
//
//  Generated by the ConcordUI command-line tool.
//

import Testing

struct FeaturesShowcaseTests {
    @Test func projectLoads() async throws {
        #expect(true)
    }
}