//
//  FeaturesShowcaseApp.swift
//  FeaturesShowcase
//
//  Generated by the ConcordUI command-line tool.
//

import ConcordUI
import ConcordUIApple
import SwiftUI

@main
struct FeaturesShowcaseApp: App {
    private let platform: ConcordApplePlatform
    private let application: FeaturesShowcaseApplication

    init() {
        let platform = ConcordApplePlatform()
        self.platform = platform

        let application = FeaturesShowcaseApplication(platform: platform)
        self.application = application
        application.startApplication()
    }

    var body: some Scene {
        ConcordAppleScene(platform: platform, application: application)
    }
}